site_name: Muna Hasan Mohamed 
theme:
  name: material
  custom_dir: overrides
  features:
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - search.share
    - content.code.annotation
    - content.code.copy
  language: en
  icon:


    logo: fontawesome/brands/github-alt
  plugins:
  - typeset
  - search
  - social

  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: black
      #accent: purple

    # Palette toggle for light mode

    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: blue
      accent: deep orange


extra:
  generator: false

  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/RBBU
    - icon: fontawesome/brands/linkedin
      link: https://dk.linkedin.com/in/2-muna

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji      
  - toc:
      permalink: true



nav:
  - Home: https://rbbu.github.io/notary/
  - Articles:
      - 'Start Here':
        - 'Start Here': index.md
      - 'Machine Learning':
        - 'Machine Learning Intro': Machine_Learning/machinelearningintro.md

copyright: |
  &copy; 2024 <a href="https://github.com/RBBU"  target="_blank" rel="noopener">Muna</a>
