site_name: Notary 
site_url: https://rbbu.github.io/notary/
site_author: Muna Hasan Mohamed
site_description: >-
  My personal hub where I share my projects and thoughts
theme:
  name: material
  custom_dir: overrides
  features:
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - search.share
    - content.code.annotation
    - content.code.copy
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.expand
    - toc.follow
    - toc.integrate
  language: en
  icon:


    logo: fontawesome/brands/github-alt
  plugins:
  - blog
  - typeset:
      typeset_html: true
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - social

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png

extra:
  generator: false
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/RBBU
    - icon: fontawesome/brands/linkedin
      link: https://dk.linkedin.com/in/2-muna


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true



nav:
  - Home: index.md
  - Knowledge Base:
      - 'Machine Learning': knowledge_base/machine_learning/index.md
      - 'Intro to Machine Learning': knowledge_base/machine_learning/intro.md
  - Blog: 
      - 'Intro': blog/index.md
      - 'Hello World': blog/hello-world.md
  - Projects:
      - 'Intro': projects/index.md
  - Book Recommendations:
      - 'Book Recommendations': book_recommendations/index.md


extra_css:
  - stylesheets/extra.css



copyright: |
  &copy; 2024 <a href="https://github.com/RBBU"  target="_blank" rel="noopener">Muna</a>
