site_name: Notary 
site_url: https://rbbu.github.io/notary/
site_author: Muna Hasan Mohamed
site_description: >-
  My personal hub where I share my projects and thoughts
theme:
  name: material
  custom_dir: overrides
  features:
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - search.share
    - content.code.annotation
    - content.code.copy
  language: en
  icon:


    logo: fontawesome/brands/github-alt
  plugins:
  - typeset
  - search
  - social

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
extra:
  generator: false

  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/RBBU
    - icon: fontawesome/brands/linkedin
      link: https://dk.linkedin.com/in/2-muna
# Plugins
plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji      
  - toc:
      permalink: true



nav:
  - Home: https://rbbu.github.io/notary/
  - Articles:
      - 'Start Here':
        - 'Start Here': index.md
      - 'Machine Learning':
        - 'Machine Learning Intro': Machine_Learning/machinelearningintro.md

copyright: |
  &copy; 2024 <a href="https://github.com/RBBU"  target="_blank" rel="noopener">Muna</a>
